/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a chat completion
         * @description Generates a model response for the given conversation. Supports streaming via `stream: true` (SSE). All responses include a `_devup` billing metadata object.
         */
        post: operations["createChatCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create embeddings
         * @description Generates embedding vectors for the given input text or array of texts. Compatible with the OpenAI embeddings API.
         */
        post: operations["createEmbedding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate images from a text prompt
         * @description Creates one or more images from a text prompt. Supports JSON and multipart/form-data request bodies. Returns a URL to the generated image hosted on DEVUP AI storage.
         */
        post: operations["createImageGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/proxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proxy a generated image URL
         * @description Fetches and proxies an image from a DEVUP AI storage URL. Returns the raw image binary with appropriate caching headers. No authentication required.
         */
        get: operations["proxyImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audio/speech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate speech from text
         * @description Converts text into spoken audio. The audio file is stored on DEVUP AI storage and a URL is returned. Billed per 1,000 characters.
         */
        post: operations["createSpeech"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audio/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe audio to text
         * @description Transcribes audio into text using speech recognition models. Accepts multipart/form-data with a `file` field containing the audio data. Billed per audio minute.
         */
        post: operations["createTranscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a video from a text prompt
         * @description Creates a video from a text prompt or edits an existing video. Supports both JSON and multipart/form-data for video editing workflows. Returns a URL to the generated video.
         */
        post: operations["createVideoGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available models
         * @description Returns a list of all published models in OpenAI-compatible format. No authentication required. Some OpenAI SDKs call this endpoint automatically on initialization.
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inference/{model_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Native model inference
         * @description A catch-all proxy endpoint that forwards any JSON payload to the specified model. The model path uses a `provider/model-name` format (e.g., `deepseek-ai/DeepSeek-V4-Pro`). The request body schema is model-dependent — consult the model's documentation for supported parameters.
         */
        post: operations["createNativeInference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account balance
         * @description Returns the current DZD balance for the authenticated user.
         */
        get: operations["getUserBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform health check
         * @description Returns the health status of the DEVUP AI platform. Returns `{"status":"ok"}` when the platform is healthy, or a 503 with `{"status":"error"}` when unhealthy.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @description Human-readable error description. */
                message: string;
                /**
                 * @description Always `devup_error`.
                 * @enum {string}
                 */
                type: "devup_error";
                /** @description Machine-readable error code. */
                code: string;
            };
        };
        /** @description Billing metadata embedded in successful metered API JSON responses and in the final chunk of SSE chat streams. Excluded from raw binary responses, Audio Transcriptions, and free utility endpoints. */
        DevUpBilling: {
            /**
             * Format: double
             * @description Cost of this request in Algerian Dinar.
             * @example 0.0012
             */
            cost_dzd: number;
            /**
             * Format: double
             * @description Remaining account balance in Algerian Dinar after this request.
             * @example 499.99
             */
            balance_dzd: number;
        };
        ChatCompletionRequest: {
            /** @description Model identifier (e.g., `deepseek-ai/DeepSeek-V4-Pro`). */
            model: string;
            /** @description The conversation history. */
            messages: components["schemas"]["ChatMessage"][];
            /** @description Maximum tokens to generate in the response. */
            max_tokens?: number;
            /** @description Sampling temperature (0–2). */
            temperature?: number;
            /** @description Nucleus sampling probability. */
            top_p?: number;
            /**
             * @description If true, returns an SSE stream of partial completions.
             * @default false
             */
            stream: boolean;
            /** @description Stop sequence(s) to end generation. */
            stop?: string | string[];
            /** @description Penalizes repeated tokens based on frequency. */
            frequency_penalty?: number;
            /** @description Penalizes tokens based on presence in the text so far. */
            presence_penalty?: number;
            /** @description A list of tools (functions) the model may call. */
            tools?: {
                [key: string]: unknown;
            }[];
            /** @description Controls which tool is called by the model. */
            tool_choice?: string | {
                [key: string]: unknown;
            };
            /** @description Response format constraint (e.g., `{"type":"json_object"}`). */
            response_format?: {
                [key: string]: unknown;
            };
        };
        ChatMessage: {
            /**
             * @description The role of the message author.
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /**
             * @description The message content (text or multimodal content parts).
             *     Assistant tool-call messages may contain content: null.
             */
            content: string | {
                [key: string]: unknown;
            }[] | null;
            /** @description Optional name for the participant. */
            name?: string;
            /** @description Tool calls generated by the assistant. */
            tool_calls?: {
                [key: string]: unknown;
            }[];
            /** @description ID of the tool call this message responds to. */
            tool_call_id?: string;
        };
        ChatCompletionResponse: {
            /** @description Unique response identifier. */
            id: string;
            /** @enum {string} */
            object: "chat.completion";
            /** @description Unix timestamp of the response. */
            created: number;
            /** @description The model used. */
            model: string;
            choices: {
                index?: number;
                message?: components["schemas"]["ChatMessage"];
                /** @enum {string} */
                finish_reason?: "stop" | "length" | "tool_calls" | "content_filter";
            }[];
            usage?: components["schemas"]["TokenUsage"];
            _devup: components["schemas"]["DevUpBilling"];
        };
        TokenUsage: {
            /** @description Tokens in the prompt. */
            prompt_tokens?: number;
            /** @description Tokens in the generated completion. */
            completion_tokens?: number;
            /** @description Total tokens used. */
            total_tokens?: number;
            prompt_tokens_details?: {
                /** @description Number of prompt tokens served from cache. */
                cached_tokens?: number;
            };
        };
        EmbeddingRequest: {
            /** @description Embedding model identifier. */
            model: string;
            /** @description Text or array of texts to embed. */
            input: string | string[];
            /**
             * @description Format of the embedding vectors.
             * @default float
             * @enum {string}
             */
            encoding_format: "float" | "base64";
        };
        EmbeddingResponse: {
            /** @enum {string} */
            object: "list";
            data: {
                /** @enum {string} */
                object?: "embedding";
                index?: number;
                /** @description The embedding vector. */
                embedding?: number[];
            }[];
            model: string;
            usage?: {
                prompt_tokens?: number;
                total_tokens?: number;
            };
            _devup: components["schemas"]["DevUpBilling"];
        };
        /**
         * @description Request schema for image editing via `multipart/form-data`.
         *     Unknown multipart fields may be forwarded transparently to the upstream provider depending on the specific model endpoint requirements.
         */
        ImageEditRequest: {
            /** @description Image generation model identifier. */
            model: string;
            /** @description Text description of the desired image edits. Forwarded transparently. */
            prompt?: string;
            /**
             * Format: binary
             * @description Base image to edit. Forwarded transparently.
             */
            image?: string;
            /**
             * Format: binary
             * @description Optional mask for inpainting. Forwarded transparently.
             */
            mask?: string;
            /**
             * @description Image dimensions (e.g., `1024x1024`, `512x512`). Forwarded transparently.
             * @default 1024x1024
             */
            size: string;
            /**
             * @description Number of images to generate.
             * @default 1
             */
            n: number;
        };
        ImageGenerationRequest: {
            /** @description Image generation model identifier. */
            model: string;
            /** @description Text description of the desired image. */
            prompt: string;
            /** @description Text description of what to avoid in the image. */
            negative_prompt?: string;
            /**
             * @description Image dimensions (e.g., `1024x1024`, `512x512`).
             * @default 1024x1024
             */
            size: string;
            /**
             * @description Number of images to generate.
             * @default 1
             */
            n: number;
            /** @description Image width in pixels (alternative to `size`). */
            width?: number;
            /** @description Image height in pixels (alternative to `size`). */
            height?: number;
            /** @description Number of diffusion steps. */
            num_inference_steps?: number;
            /** @description Classifier-free guidance scale. */
            guidance_scale?: number;
            /** @description Random seed for reproducibility. */
            seed?: number;
        };
        ImageGenerationResponse: {
            data: {
                /**
                 * Format: uri
                 * @description URL of the generated image.
                 */
                url?: string;
            }[];
            _devup: components["schemas"]["DevUpBilling"];
        };
        SpeechRequest: {
            /** @description TTS model identifier. */
            model: string;
            /** @description The text to synthesize into speech. */
            input: string;
            /**
             * @description Voice preset to use.
             * @default aura-asteria-en
             */
            voice: string;
            /**
             * @description Audio output format.
             * @default mp3
             * @enum {string}
             */
            response_format: "mp3" | "opus" | "aac" | "flac" | "wav" | "pcm";
            /**
             * Format: uri
             * @description Public HTTPS URL to a reference audio file for voice cloning.
             *     Required only when the selected model uses voice-cloning mode (AUDIO_REFERENCE).
             *     Validated against SSRF rules before any fetch — must be a publicly reachable HTTPS URL.
             *     Ignored by models that do not support AUDIO_REFERENCE.
             */
            referenceAudioUrl?: string;
        };
        SpeechResponse: {
            /**
             * Format: uri
             * @description URL of the generated audio file.
             */
            url: string;
            _devup: components["schemas"]["DevUpBilling"];
        };
        TranscriptionRequest: {
            /**
             * Format: binary
             * @description The audio file to transcribe (multipart file upload).
             */
            file: string;
            /**
             * @description Speech recognition model identifier.
             * @default openai/whisper-large-v3-turbo
             */
            model: string;
            /** @description ISO-639-1 language code to hint the recognizer. */
            language?: string;
            /**
             * @description Format of the transcription response. The route always requests `verbose_json`
             *     from the upstream provider internally (for accurate billing and segment data),
             *     then converts to the client-requested format before returning.
             *     Unknown values default to `json`. `text`, `srt`, and `vtt` are returned as
             *     `text/plain`; `json` and `verbose_json` are returned as `application/json`.
             * @default json
             * @enum {string}
             */
            response_format: "json" | "verbose_json" | "text" | "srt" | "vtt";
        };
        TranscriptionResponse: {
            /** @description The transcribed text. */
            text: string;
        };
        TranscriptionVerboseResponse: {
            /** @description The transcribed text. */
            text: string;
            /** @description Total audio duration in seconds. */
            duration: number;
            segments: {
                [key: string]: unknown;
            }[];
        };
        VideoGenerationRequest: {
            /** @description Video generation model identifier. */
            model: string;
            /** @description Text description of the desired video. */
            prompt: string;
            /** @description Text description of what to avoid. */
            negative_prompt?: string;
            /** @description Number of frames to generate. */
            num_frames?: number;
            /** @description Video width in pixels. */
            width?: number;
            /** @description Video height in pixels. */
            height?: number;
            /** @description Random seed for reproducibility. */
            seed?: number;
        };
        VideoEditRequest: {
            /** @description Video editing model identifier. */
            model: string;
            /**
             * Format: binary
             * @description Source video file for editing.
             */
            video: string;
            /** @description Text prompt describing the edit (required for text_prompt mode). */
            prompt?: string;
            /**
             * Format: binary
             * @description Mask video for region-based editing (mask_video mode).
             */
            mask?: string;
            /**
             * Format: uri
             * @description Public HTTPS URL to the mask video (alternative to uploading mask binary).
             */
            mask_url?: string;
            /**
             * @description JSON-encoded string representing an array of key-point objects for key_points mode.
             *     Each object must have numeric `x`, `y` coordinates and a `type` of either `"positive"` or `"negative"`.
             *     Example: `"[{\"x\":100,\"y\":200,\"type\":\"positive\"}]"`
             *     The route calls JSON.parse() on this field before forwarding.
             */
            key_points?: string;
            /**
             * @description Frame index for key_points editing mode.
             * @default 0
             */
            frame_index: number;
            /**
             * @description Whether to auto-trim the output video.
             * @default false
             */
            auto_trim: boolean;
            /**
             * @description Whether to preserve the original audio track in the output.
             * @default true
             */
            preserve_audio: boolean;
            /**
             * @description Background fill color (background_color mode). CSS color name or hex value.
             * @default White
             */
            background_color: string;
            /**
             * @description Upscale factor for upscale_factor mode. Only 2 or 4 are accepted; other values are coerced to 2.
             * @default 2
             * @enum {integer}
             */
            desired_increase: 2 | 4;
            /** @description Output container and codec string forwarded to the upstream provider. */
            output_container_and_codec?: string;
        };
        VideoGenerationResponse: {
            data: {
                /**
                 * Format: uri
                 * @description URL of the generated or edited video.
                 */
                url: string;
            }[];
            _devup: components["schemas"]["DevUpBilling"];
        };
        ModelListResponse: {
            /** @enum {string} */
            object: "list";
            data: components["schemas"]["ModelObject"][];
        };
        ModelObject: {
            /** @description Model identifier (slug or provider model ID). */
            id: string;
            /** @enum {string} */
            object: "model";
            /** @description Unix timestamp of model creation. */
            created: number;
            /** @enum {string} */
            owned_by: "devupai";
        };
        BalanceResponse: {
            /**
             * Format: double
             * @description Current account balance in Algerian Dinar (DZD).
             */
            balance_dzd: number;
        };
        HealthResponse: {
            /**
             * @description Platform health status.
             * @enum {string}
             */
            status: "ok" | "error";
        };
    };
    responses: {
        /** @description Invalid request body or parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "message": "The \"model\" field is required.",
                 *         "type": "devup_error",
                 *         "code": "missing_model"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Missing, empty, or revoked API key.
         *     This response covers three distinct codes depending on the authentication path:
         *     - `missing_api_key`: Authorization header absent or Bearer token is empty.
         *     - `invalid_api_key`: Key not found, deactivated, or failed validation.
         *     - `token_revoked`: The scoped JWT credential has been explicitly revoked.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Account suspended or scoped credential does not permit the requested model.
         *     - `account_suspended`: The DEVUP account is suspended; all requests are blocked.
         *     - `model_not_allowed`: The scoped credential does not grant access to the requested model.
         *       This code is never returned for unrestricted master API keys.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description DZD balance depleted or scoped credential budget exhausted.
         *     - `insufficient_balance`: The DEVUP account has insufficient available balance.
         *     - `budget_exhausted`: The scoped credential has reached its configured budget.
         *       This code is never returned for unrestricted master API keys.
         */
        InsufficientBalance: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded (100 requests per 60-second sliding window per account). */
        RateLimited: {
            headers: {
                /** @description Maximum requests allowed in the current window. */
                "X-RateLimit-Limit"?: number;
                /** @description Remaining requests in the current window. */
                "X-RateLimit-Remaining"?: number;
                /** @description Unix timestamp (ms) when the current window resets. */
                "X-RateLimit-Reset"?: number;
                /** @description Seconds until the rate limit resets. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "message": "Rate limit exceeded. Please slow down your requests and try again shortly.",
                 *         "type": "devup_error",
                 *         "code": "rate_limit_exceeded"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The inference pipeline encountered a transient error. */
        ComputeError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "message": "The DEVUP AI Inference Pipeline encountered a transient error. Please retry your request.",
                 *         "type": "devup_error",
                 *         "code": "DEVUP_COMPUTE_ERROR"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected internal error occurred. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "message": "Internal server error.",
                 *         "type": "devup_error",
                 *         "code": "internal_error"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The DEVUP AI Gateway is temporarily unable to process requests (rate-limiter backend unavailable). */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "message": "The DEVUP AI Gateway is temporarily unable to process requests. Please try again shortly.",
                 *         "type": "devup_error",
                 *         "code": "service_unavailable"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createChatCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "model": "deepseek-ai/DeepSeek-V4-Pro",
                 *       "messages": [
                 *         {
                 *           "role": "user",
                 *           "content": "Hello from Algeria!"
                 *         }
                 *       ],
                 *       "max_tokens": 256,
                 *       "stream": false
                 *     }
                 */
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful chat completion (non-streaming). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "devup-12345678-abcd-1234-abcd-1234567890ab",
                     *       "object": "chat.completion",
                     *       "created": 1700000000,
                     *       "model": "deepseek-ai/DeepSeek-V4-Pro",
                     *       "choices": [
                     *         {
                     *           "index": 0,
                     *           "message": {
                     *             "role": "assistant",
                     *             "content": "Hello! How can I help you today?"
                     *           },
                     *           "finish_reason": "stop"
                     *         }
                     *       ],
                     *       "usage": {
                     *         "prompt_tokens": 10,
                     *         "completion_tokens": 8
                     *       },
                     *       "_devup": {
                     *         "cost_dzd": 0.0012,
                     *         "balance_dzd": 500
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ChatCompletionResponse"];
                    "text/event-stream": string;
                };
            };
            /** @description Invalid request body or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["InsufficientBalance"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["ComputeError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createEmbedding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "model": "Qwen/Qwen3-Embedding-8B",
                 *       "input": "Hello world",
                 *       "encoding_format": "float"
                 *     }
                 */
                "application/json": components["schemas"]["EmbeddingRequest"];
            };
        };
        responses: {
            /** @description Embedding vectors generated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "object": "list",
                     *       "data": [
                     *         {
                     *           "object": "embedding",
                     *           "index": 0,
                     *           "embedding": [
                     *             0.0023,
                     *             -0.0091,
                     *             0.0152
                     *           ]
                     *         }
                     *       ],
                     *       "model": "Qwen/Qwen3-Embedding-8B",
                     *       "usage": {
                     *         "prompt_tokens": 2,
                     *         "total_tokens": 2
                     *       },
                     *       "_devup": {
                     *         "cost_dzd": 0.0001,
                     *         "balance_dzd": 500
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["EmbeddingResponse"];
                };
            };
            /** @description Invalid request body or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["ComputeError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createImageGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "model": "stabilityai/stable-diffusion-xl-base-1.0",
                 *       "prompt": "A futuristic city skyline at sunset",
                 *       "size": "1024x1024",
                 *       "n": 1
                 *     }
                 */
                "application/json": components["schemas"]["ImageGenerationRequest"];
                /**
                 * @example {
                 *       "model": "stabilityai/stable-diffusion-xl-base-1.0",
                 *       "prompt": "A futuristic city skyline at sunset",
                 *       "image": "<binary data>",
                 *       "size": "1024x1024",
                 *       "n": 1
                 *     }
                 */
                "multipart/form-data": components["schemas"]["ImageEditRequest"];
            };
        };
        responses: {
            /** @description Image generated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "url": "https://api.devupai.com/storage/generations/img_example_1700000000.png"
                     *         }
                     *       ],
                     *       "_devup": {
                     *         "cost_dzd": 5,
                     *         "balance_dzd": 495
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ImageGenerationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["ComputeError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    proxyImage: {
        parameters: {
            query: {
                /**
                 * @description The full URL of the image to proxy. Must be from an allowed domain.
                 * @example https://api.devupai.com/storage/generations/img_example.png
                 */
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image binary data. */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                    "image/webp": string;
                    "image/gif": string;
                };
            };
            /** @description Missing or invalid URL parameter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example Missing URL */
                    "text/plain": string;
                };
            };
            /** @description Domain not in the allowlist. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example Forbidden: Domain not allowed */
                    "text/plain": string;
                };
            };
            /** @description Failed to fetch the upstream image. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example Failed to load image */
                    "text/plain": string;
                };
            };
        };
    };
    createSpeech: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "model": "tts-1",
                 *       "input": "Welcome to DEVUP AI, the gateway to open-source models.",
                 *       "voice": "aura-asteria-en",
                 *       "response_format": "mp3"
                 *     }
                 */
                "application/json": components["schemas"]["SpeechRequest"];
            };
        };
        responses: {
            /** @description Audio generated and stored successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "url": "https://api.devupai.com/storage/audio/tts_example_1700000000.mp3",
                     *       "_devup": {
                     *         "cost_dzd": 0.5,
                     *         "balance_dzd": 499.5
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SpeechResponse"];
                };
            };
            /** @description Invalid request body or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["ComputeError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createTranscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["TranscriptionRequest"];
            };
        };
        responses: {
            /** @description Transcription completed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "text": "Hello, this is a test recording.",
                     *       "duration": 2.5,
                     *       "segments": [
                     *         {
                     *           "start": 0,
                     *           "end": 2.5,
                     *           "text": "Hello, this is a test recording."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["TranscriptionResponse"] | components["schemas"]["TranscriptionVerboseResponse"];
                    /** @example Hello, this is a test recording. */
                    "text/plain": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["ComputeError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createVideoGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "model": "example-org/example-video-model",
                 *       "prompt": "A cat astronaut floating in space"
                 *     }
                 */
                "application/json": components["schemas"]["VideoGenerationRequest"];
                "multipart/form-data": components["schemas"]["VideoEditRequest"];
            };
        };
        responses: {
            /** @description Video generated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "url": "https://api.devupai.com/storage/generations/vid_example_1700000000.mp4"
                     *         }
                     *       ],
                     *       "_devup": {
                     *         "cost_dzd": 25,
                     *         "balance_dzd": 475
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["VideoGenerationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["InsufficientBalance"];
            /** @description Rate limit or concurrency limit exceeded. This endpoint applies two independent limits: (1) 100 requests per 60-second sliding window per account — returns standard rate-limit headers. (2) 150 globally in-flight video generation requests — when this threshold is exceeded, a 429 is returned with Retry-After: 10 and no rate-limit headers. */
            429: {
                headers: {
                    /** @description Seconds to wait before retrying (10 for concurrency limit; varies for rate limit). */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            502: components["responses"]["ComputeError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model list retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "object": "list",
                     *       "data": [
                     *         {
                     *           "id": "deepseek-ai/DeepSeek-V4-Pro",
                     *           "object": "model",
                     *           "created": 1700000000,
                     *           "owned_by": "devupai"
                     *         },
                     *         {
                     *           "id": "Qwen/Qwen3-Embedding-8B",
                     *           "object": "model",
                     *           "created": 1700000100,
                     *           "owned_by": "devupai"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
            /** @description Endpoint not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createNativeInference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The model identifier in `org/model-name` format. Model identifiers may contain slash-separated segments. Generated SDKs may percent-encode `/` as `%2F`. DEVUP accepts both literal slash-separated paths and percent-encoded slash values (e.g., `deepseek-ai/DeepSeek-V4-Pro` or `deepseek-ai%2FDeepSeek-V4-Pro`).
                 * @example deepseek-ai/DeepSeek-V4-Pro
                 */
                model_path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "input": "Hello from Algeria!"
                 *     }
                 */
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Inference completed successfully. Response schema is model-dependent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "output": "Example model output",
                     *       "_devup": {
                     *         "cost_dzd": 0.05,
                     *         "balance_dzd": 499.95
                     *       }
                     *     }
                     */
                    "application/json": {
                        _devup?: components["schemas"]["DevUpBilling"];
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["ComputeError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getUserBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "balance_dzd": 500
                     *     }
                     */
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Endpoint not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Platform is unhealthy. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "error"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
